###
GET http://localhost:8080/api/books/
###
GET http://localhost:8080/api/books/27
###
POST http://localhost:8080/api/books/
Content-Type: application/json

{
  "title": "The Hobbit",
  "description": "A book about a hobbit"
}

###
DELETE http://localhost:8080/api/books/26
###